# Generated by Django 2.0.3 on 2018-03-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default name', max_length=50)),
                ('content', models.CharField(default='default content', max_length=500)),
                ('user_name', models.CharField(default='default name', max_length=10)),
                ('create_at', models.IntegerField(default='1514879938')),
                ('user_id', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.IntegerField(default=1)),
                ('user_id', models.IntegerField(default=1)),
                ('user_name', models.CharField(default='default name', max_length=10)),
                ('content', models.CharField(default='default content', max_length=500)),
                ('create_at', models.IntegerField(default='1514879938')),
            ],
        ),
    ]
