# Generated by Django 2.0.3 on 2018-03-24 06:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(default='第一次登陆', max_length=20)),
                ('sex', models.CharField(default='男', max_length=3)),
                ('birthday', models.CharField(default='1970-01-01', max_length=20)),
                ('job_number', models.CharField(default='0001', max_length=10)),
                ('zhengzhi_mianmao', models.CharField(default='群众', max_length=10)),
                ('zhengzhi_time', models.CharField(default='1970-01-01', max_length=20)),
                ('job', models.CharField(default='工程师', max_length=30)),
                ('job_time', models.CharField(default='1970-01-01', max_length=20)),
                ('job_2', models.CharField(default='员工', max_length=30)),
                ('id_number', models.CharField(default='400000197001010000', max_length=30)),
                ('xue_li', models.CharField(default='本科', max_length=30)),
                ('school', models.CharField(default='青蛙大学', max_length=30)),
                ('graduate_time', models.CharField(default='1970-01-01', max_length=20)),
                ('job_join_time', models.CharField(default='1970-01-01', max_length=20)),
                ('team_belong', models.CharField(default='C640', max_length=20)),
                ('phone', models.CharField(default='1333333333333', max_length=30)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
                ('user_type', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'abstract': False,
                'swappable': 'AUTH_USER_MODEL',
            },
        ),
    ]
